DROP DATABASE IF EXISTS prueba;
CREATE DATABASE prueba;
USE prueba;
CREATE TABLE USUARIOS(
ID INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(50),
PASS VARCHAR(15)
);

CREATE TABLE REPVENTAS(
ID INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
VENTAS INT,
SALARIO DECIMAL(11,2)
);

CREATE TABLE REPSERVICIOS(
ID INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
SERVICIO VARCHAR(50),
SALARIO DECIMAL(11,2)
);

CREATE TABLE CLIENTES(
ID INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
DNI VARCHAR(9) UNIQUE
);

CREATE TABLE PERSONAS(
ID INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(50),
TIPO VARCHAR(40),
SEXO VARCHAR(18),
COMENTARIOS VARCHAR(250),
ID_VENTAS INT,
ID_SERVICIO INT,
ID_CLIENTE INT,
FOREIGN KEY (ID_VENTAS) REFERENCES REPVENTAS(ID),
FOREIGN KEY (ID_SERVICIO) REFERENCES REPSERVICIOS(ID),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
);

