/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import conexion.EstablecerConexionDB;
import javax.swing.*;
import java.sql.*;
import javax.sound.sampled.*;
import personas.*;
import sonido.Sonidos;

/**
 *
 * @author shiba
 */
public class VentanaConsulta extends JFrame implements Sonidos {

    /**
     * Creates new form VentanaInicio
     */
    public VentanaConsulta() {
        initComponents();
        setTitle("Microsoft Software");
        setResizable(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        busqueda = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        volver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoComentarios = new javax.swing.JTextArea();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        busqueda.setBackground(new java.awt.Color(0, 0, 255));
        busqueda.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        busqueda.setForeground(new java.awt.Color(255, 255, 255));
        busqueda.setText("BUSCAR");
        busqueda.setFocusable(false);
        busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busquedaActionPerformed(evt);
            }
        });
        jPanel2.add(busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 180, 40));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        volver.setBackground(new java.awt.Color(0, 0, 255));
        volver.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        volver.setForeground(new java.awt.Color(255, 255, 255));
        volver.setText("VOLVER");
        volver.setFocusable(false);
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel2.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 130, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID DEL PERSONAL");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        campoComentarios.setEditable(false);
        campoComentarios.setColumns(20);
        campoComentarios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        campoComentarios.setRows(5);
        campoComentarios.setFocusable(false);
        jScrollPane1.setViewportView(campoComentarios);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 690, 230));

        jSpinner1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel2.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 70, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 730, 450));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MICROSOFT SYSTEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/microsoft.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        VentanaPrincipal vP = new VentanaPrincipal();
        reproducirSonido("disparo.wav");
        this.dispose();
        vP.setVisible(true);
    }//GEN-LAST:event_volverActionPerformed

    private void busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busquedaActionPerformed
        reproducirSonido("disparo.wav");
        int seguro = JOptionPane.showConfirmDialog(null, "¿Está usted seguro de buscar a este usuario?",
                "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (seguro == JOptionPane.YES_OPTION) {
            try {
                Connection cn = EstablecerConexionDB.conectar();
                PreparedStatement consultar = cn.prepareStatement("SELECT TIPO FROM PERSONAS WHERE ID=?");
                consultar.setInt(1, Integer.parseInt(jSpinner1.getValue().toString()));
                ResultSet rs = consultar.executeQuery();
                if (rs.next()) {
                    switch (rs.getString(1)) {
                        case "Dept.Ventas":
                            PreparedStatement devolverVentas = cn.prepareStatement("SELECT NOMBRE,SEXO,COMENTARIOS,ID_VENTAS FROM PERSONAS WHERE ID=?");
                            devolverVentas.setInt(1, Integer.parseInt(jSpinner1.getValue().toString()));
                            ResultSet rsVentas = devolverVentas.executeQuery();
                            if (rsVentas.next()) {
                                DeptVentas dV = new DeptVentas();
                                dV.setNombre(rsVentas.getString(1));
                                dV.setSexo(rsVentas.getString(2));
                                dV.setComentario(rsVentas.getString(3));
                                PreparedStatement consultarVentas = cn.prepareStatement("SELECT VENTAS,SALARIO FROM repventas WHERE ID=?");
                                consultarVentas.setInt(1, rsVentas.getInt(4));
                                ResultSet devolverSalVent = consultarVentas.executeQuery();
                                if (devolverSalVent.next()) {
                                    dV.setVentas(devolverSalVent.getInt(1));
                                    dV.setSalario(devolverSalVent.getInt(2));
                                    campoComentarios.setText("Nombre: " + dV.getNombre() + "\nSexo: " + dV.getSexo() + "\nSalario: " + dV.getSalario() + "€\nNúmero de ventas: " + dV.getVentas() + "\nComentario: " + dV.getComentario() + "\nDescripción del tipo de persona: " + dV.devolverDescripcion());
                                }
                            }

                            break;
                        case "Dept.Servicio":

                            PreparedStatement devolverServicios = cn.prepareStatement("SELECT NOMBRE,SEXO,COMENTARIOS,ID_SERVICIO FROM PERSONAS WHERE ID=?");
                            devolverServicios.setInt(1, Integer.parseInt(jSpinner1.getValue().toString()));
                            ResultSet rsServicio = devolverServicios.executeQuery();
                            if (rsServicio.next()) {
                                DeptServicio dV = new DeptServicio();
                                dV.setNombre(rsServicio.getString(1));
                                dV.setSexo(rsServicio.getString(2));
                                dV.setComentario(rsServicio.getString(3));
                                PreparedStatement consultarServicios = cn.prepareStatement("SELECT SERVICIO,SALARIO FROM repservicios WHERE ID=?");
                                consultarServicios.setInt(1, rsServicio.getInt(4));
                                ResultSet devolverSalVent = consultarServicios.executeQuery();
                                if (devolverSalVent.next()) {
                                    dV.setTipoServicio(devolverSalVent.getString(1));
                                    dV.setSalario(devolverSalVent.getInt(2));
                                    campoComentarios.setText("Nombre: " + dV.getNombre() + "\nSexo: " + dV.getSexo() + "\nSalario: " + dV.getSalario() + "€\nServicio ofrecido: " + dV.getTipoServicio() + "\nComentario: " + dV.getComentario() + "\nDescripción del tipo de persona: " + dV.devolverDescripcion());
                                }
                            }
                            break;
                        case "Cliente":
                            PreparedStatement devolverCliente = cn.prepareStatement("SELECT NOMBRE,SEXO,COMENTARIOS,ID_CLIENTE FROM PERSONAS WHERE ID=?");
                            devolverCliente.setInt(1, Integer.parseInt(jSpinner1.getValue().toString()));
                            ResultSet rsCliente = devolverCliente.executeQuery();
                            if (rsCliente.next()) {
                                Clientes dV = new Clientes();
                                dV.setNombre(rsCliente.getString(1));
                                dV.setSexo(rsCliente.getString(2));
                                dV.setComentario(rsCliente.getString(3));
                                PreparedStatement consultarCliente = cn.prepareStatement("SELECT DNI FROM clientes WHERE ID=?");
                                consultarCliente.setInt(1, rsCliente.getInt(4));
                                ResultSet devolverSalVent = consultarCliente.executeQuery();
                                if (devolverSalVent.next()) {
                                    dV.setDNI(devolverSalVent.getString(1));
                                    campoComentarios.setText("Nombre: " + dV.getNombre() + "\nSexo: " + dV.getSexo() + "\nDNI del cliente: " + dV.getDNI() + "\nComentario: " + dV.getComentario() + "\nDescripción del tipo de persona: " + dV.devolverDescripcion());
                                }
                            }
                            break;
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "No se ha encontrado ningún usuario.", "Mensaje de error", JOptionPane.ERROR_MESSAGE);
                }
                cn.close();
            } catch (SQLException e) {
                System.err.println("Error al encontrar: " + e);
            }
        }
    }//GEN-LAST:event_busquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsulta.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsulta().setVisible(true);
            }
        });
    }

    @Override
    public void reproducirSonido(String sonido) {
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(VentanaInicio.class.getResourceAsStream("/sonido/" + sonido));
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton busqueda;
    private javax.swing.JTextArea campoComentarios;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
